Donkie/SpoolmanDB

- filaments/fillamentum.json
This includes all colours. Data sourced from manufacturer website with exception of colours where some were unspecified. Unspecified colours sourced from https://filamentcolors.xyz/ with the exception of two which were unfindable anywhere so I estimated using the print photos they included.
> Add range of Fillamentum Extrafill ASA filaments to DB

- materials.json
This adds some 3D printable high-end polymers and their densities, that were not yet added to the materials.json file.
I will add more once I go through more of my inventory.
The rationale behind 022fb6383788e4e4f883cc30060d3444bbca2243 is that by largely adopted convention the names of the polymers are written first, than their commercial/everyday name.
While I like it better like this, 022fb6383788e4e4f883cc30060d3444bbca2243 can be easily reverted if you don't agree.
> materials: add technopolymers

- filaments/formfutura.json
This is the first leg of Formfutura filaments, using the `spool_type` key for the cardboard spools.
NOTE: I have the material name in the name of the filament since "ePLA" is not really any different to regular PLA, just a different plastic blend they make.
EDIT: I can resubmit with one commit if you want, I had quite a few errors I didn't notice
> filaments: add Formfutura EasyFIl PLA / ePLA line

- filaments/bambulab.json
I'm not sure about the name I gave (PA6-GF) as it is the name Bambu uses. They also have carbon fiber alternative (PA6-CF). You have `Nylon` in the materials file, hence my doubt.
> Add Bambu Lab PA6-GF filament colors

- filaments/3dxtech.json
I took a pass at a baseline set of 3dxtech filaments. It was quite a wrestle to put the data into the JSON format without any tools. Please give it a good look to ensure the format is correct.
It would be great if someone skilled in the art made a tool where data could be entered, validated, and committed locally to a JSON file in order to facilitate data entry. Setting up a standard excel table and python to ingest could also work.
My reference mats:
[3dxtech_reference_links_table.csv](https://github.com/Donkie/SpoolmanDB/files/15401800/3dxtech_reference_links_table.csv)
> Selection of 3dxtech filaments

- filaments.schema.json
- filaments/3dxtech.json
- filaments/formfutura.json
this should cut it, I don't know how can I run the deploy workflows for testing though, do I have to cherry pick this to my main branch? 🤔
> feat: implement #19

- filaments/prusament.json
I added most of the currently available Prusament PETG filaments that had official HEX colors on their product page.
Additionally I've adapted the spool weight to 193g as this seems to be the correct weight.
This is also shown for the spools that I currently have:
* https://prusament.com/spool/?spoolId=672ad5d69f
* https://prusament.com/spool/?spoolId=48bf6b769d
* https://prusament.com/spool/?spoolId=f22e1f2005
* https://prusament.com/spool/?spoolId=ad56bbbd97
> Add further Prusament PETG filaments

- filaments/jayo.json
- filaments/sunlu.json
The filaments are actually the same but they come on a 1kg plastic spool from sunlu or a 1.1kg cardboard spool from Jayo.
> Add Silk TPU and Glow PLA filaments from Sunlu and Jayo.

- filaments.schema.json
- filaments/qiditech.json
hi,
#1 im a sysadmin, not a dev, so i am not very experienced with git and github procedures :)
#2 the JSON editor i am using (JSONBuddy) complains about the pattern for the filament name. i believe what i changed is the correct way to do it, but i am painfully aware that different validators work differently and the original pattern might have validated fine in others... still, if it doesn't break yours, i guess this is more "universal"
#3 the list for QIDI is not exhaustive, i just added those that i had ordered, will probably add more in the future
#4 what do you think about adding a "list price" to the definition? or was that left out on purpose?
thanks & kr
> add QIDITech (PAHT|PPS)-CF

- filaments/r3d.json
Added r3d.json for filaments from [R3D](https://www.r3dprinter.com/)
a popular manufacturer of affordable 3D printing filaments widely used in Thailand. 
The file includes details on PETG and PLA filaments.
> Add R3D filament

- filaments/r3d.json
The spool weight has been adjusted from 100g to 140g to align with the latest specifications.
> Updated R3D Filament with New Cardboard Spool Weight

- filaments/extrudr.json
- filaments/fillamentum.json
- filaments/flashforge.json
- filaments/polymaker.json
This PR contains the following changes:
- Add Polymaker PolyLite™ PLA (non-pro)
- Addition of FlashForge PLA and PLA Pro filaments
- Modification to Extrudr PETG Glowex entry as this is sold in a smaller spool and has slightly different characteristics to the normal PETG range
> PolyLite (Non-Pro), FlashForge and Extruder Additions and Changes

- filaments/bambulab.json
Just a simple update to support a new color Bambu offers. Color data from https://us.store.bambulab.com/collections/bambu-lab-3d-printer-filament/products/pla-silk-dual-color
> Added new dual silk color Velvet Eclipse

- filaments.schema.json
In release [0.31.0](https://github.com/python-jsonschema/check-jsonschema/releases/tag/0.31.0) of check-jsonschema regular expressions now use unicode mode by default. A summary of difference can be found [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicode#description). In SpoolmanDB's case that means that patterns in the schema file can no longer escape any character that is not an actual escape sequence like before. In unicode-aware-mode those would've been "identity escapes"
> An escape sequence that's not recognized becomes an ["identity escape"](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Character_escape).
now they are just straight up forbidden. I removed the backslashes for the illegal `-` …
> remove illegal escape sequence

- filaments/overture.json
Based on TDS and information from https://overture3d.com/products/overture-tpu-high-speed-filament-1-75mm
Cardboard spool weight is the heaviest found for their cardboard spools - I don't have an empty handy
> Add Overture High Speed TPU

- filaments/creality.json
Rainbow CR 
https://store.creality.com/au/products/cr-1-75mm-pla-3d-printing-filament-1kg?spm=..product_95c043b9-c56e-4fec-a7fb-4c0d7194fe36.header_1.1&spm_prev=..product_57e00e12-39d8-4f32-8641-2e3247a963b0.header_1.1
The CR PLA is labelled as just PLA in the file - Creality sells lots of different sub-types with slightly different costs & profiles so this can be confusing. Didn't update it to avoid breaking things
Ender-PLA - Blue and red available occasionally, colours match CR PLA but are more matt (but it's not listed as matt)
https://store.creality.com/au/products/ender-pla-value-pack2-spools-pack?spm=..product_57e00e12-39d8-4f32-8641-2e3247a963b0.header_1.1
> Creality Rainbow CR & Ender-PLA

- filaments/bambulab.json
Add Bambu Lab:
- Support for PLA/PETG
- Support for PLA
- Support for ABS
- Support for PA/PET
> Add Bambu Lab Support Materials

- filaments/eryone.json
I was already working on this before #106 got created but noticed that #106 had incorrect values like 90 for bed temp on PLA. I took what was in that PR (Fixed the values) and added what I already was working on to make one PR. 
My spool weights are set to 187 (Some spools are cardboard some are plastic) Ive seen some colors come in both plastic and/or cardboard so based on these value https://www.printables.com/model/464663-empty-spool-weight-catalog 187 is the logical choice as it fits with both cardboard and plastic.
The hex codes I tried my best to find proper codes but Eryone doesn't seem to have hex codes anywhere. I pulled data from 
https://filamentcolors.xyz/library/?f=Eryone and some hexes I just used generic color hexes
> Created Eryone (PLA, PETG, & Silk PLA)

- filaments/bambulab.json
This filament is discontinued, being replaced by "Support for PLA/PETG", however Bambu Lab is now encoding these new spools with the RFID data saying its 'Support for PLA' (i.e. not showing the /PETG). This is seeing the new Support PLA/PETG incorrectly identifying as 'Support for PLA'
Given Support for PLA is no longer sold, to avoid this issue, 'Support for PLA' is being removed. 
Additionally the new 'Support for PLA/PETG' is supposed to be available in "Nature" (Colour is a semi translucent White, so hex code = FFFFFF) and Black (hex code = 000000). However, it appears Bambu is shipping these spools with the RFID hex codes reversed. So for now, these hex codes are being swapped, IF/WHEN Bambu starts shipping these spools with the correctly matched hex codes, these can be reversed back …
> Remove - Support for PLA (Discontinued & Conflicts with PLA/PETG)

- filaments/sunlu.json
Hey there,
not sure if this is the correct way to add these. The other Sunlu PLAs where with glow: true. I did no merge them into one list because they have different densities (I checked in Sunlu's Filament Technical Data Sheet (TDS): https://3dsunlu.com/pages/materials).
These are the ones without glow. You can find them here: https://3dsunlu.com/products/sunlu-pla-filament?variant=51742515101987
I only added those that I could find on https://filamentcolors.xyz/library/?f=&mfr=sunlu&ft=pla where the name matched the one in the Sunlu website. The spool weight comes from https://www.reddit.com/r/BambuLab/comments/1f9241i/sunlu_pla_20_spool_weight/ as this is the spool that I got with the black PLA. They are reusable.
> Add Sunlu PLA non-glow

- filaments/overture.json
I added the Overture ABS filaments since they seemed to be missing. Everything aside from the spool weight was retrieved from Overture's website. The spool weight is based on the indicated weight of a real spool of Overture ABS that I recently purchased, I was unable to find any indication of the spool weight on Overture's website.
> Overture ABS

- filaments/elegoo.json
Information pulled from https://us.elegoo.com/products/asa-filament-1-75mm-colored-1kg, temperatures are midpoints of stated ranges.
> Add Elegoo ASA B+W

- .github/workflows/build.yml
Remove the need to update entire os of build host, in testing it drops about a minute off the build time.
> Use python3 to install pipx

- filaments/elegoo.json
This is the "standard" PLA+ (not the same as the Rapid-PLA+). https://uk.elegoo.com/products/elegoo-pla-plus-3d-printer-filament-1-75mm-colored-1kg
I also ran the file through jq to just tidy up the indentation, as it was a bit weird and mixture of different indentations. I hope that's OK!
> Add Elegoo PLA+ 

- filaments/elegoo.json
Updated from the elegoo website. Why is black not #000000? [I don't know, take it up with elegoo.](https://us.elegoo.com/products/pla-matte-filament-1-75mm-colored-1kg?variant=43734199664821)
> update elegoo matte PLA filaments

- filaments/polymaker.json
PolyTerra PLA is now Panchroma Matte PLA. https://us.polymaker.com/products/panchroma-matte
- adjusted the name to align with the polymaker 
- added colors that were not present
- updated hex codes to align with the stated hex codes from the polymaker specs
- updated hex codes that were set to white to the hex code used to represent the color on the polymaker site
> Polymaker panchroma matte updates

- filaments.schema.json
- filaments/elegoo.json
The cardboard spool weight is exactly 154g. Tested with 5 different cardboard spools that I have fully empty.
- Added PLA Marble and rename "Clear" to "Translucent" (I've followed the Elegoo official page)
- Added every Elegoo Silk PLA (at least at this moment) and the spool should weight 154 too, based on the page, I doesn't have any empty plastic spool so I can't check this. Maybe I will update this in the future.
- Added "Silver" to the Rapid PLA+
- Changed the density based on the official ELEGOO Specification.
> Updated Elegoo filaments.
