filaments/bambulab.json
Sorry for all the pulls, I prefer to make small changes at a time to be able to clearly see what's changing.
=> Fix Bambu Lab filament diameter to only 1.75

filaments/bambulab.json
I think the only colors missing are the ones with dual colors.
=> Add Bambu Lab Silk, Metallic, Galaxy, Sparkle, Marble and Glow PLA colors

filaments/bambulab.json
=> Split Bambu Lab PLA filaments into categories to be able to use the finish property

filaments/prusament.json
referenced https://www.onlyspoolz.com/portfolio/spool-prusa-prusament-petg2/
=> fix(filaments): add spool weight for Prusament PETG

public/index.html, public/styles.css
Instead of being useful and adding filaments and materials I've procrastinated what little time I had in styling up the webpage...
Preview here: https://stuserious.github.io/SpoolmanDB/
Let me know what you think, I think we can improve it quite a bit but it's a start ;)
=> feat(webpage): add basic CSS styling to the webpage

filaments/ratrig.json
I haven't added empty spool weight yet, will update as soon I finish a spool or as someone on discord can hook me up with the weight :)
=> filaments: add RatRig filaments

filaments/3djake.json, filaments/overture.json
=> Add Overture PETG and 3dJake PETG and PCTG 1.75mm

filaments/dasfilament.json
Note, that the color names are only in german. That is intended, see here:
https://www.dasfilament.de/filament-refill/petg-1-75-mm/?p=1&o=10
=> Add dasfilament filaments

filaments/catyarn.json, filaments/hatchbox.json, filaments/sunlu.json
Added various colour of the following brands:
Hatchbox
Cat Yarn
Sunlu
=> Added various filaments to the database

filaments/esun.json, materials.json
added esun`s ABS+ with hexcodes from theis website https://www.esun3d.com/abs-pro-product/
=> add esun ABS+

filaments/esun.json
Hey there, 
Thanks a lot for this database it's very convenient!
I added the filament eTPU-95A from eSun available here https://www.esun3d.com/etpu-95a-product/
=> Added eSun TPU (95A)

filaments/cr3d.json
First batch of filaments from local German manufacturer CR3D https://www.cr3d.de/kategorie/filamente/
ABS
PETG
ABS FibCR20
=> First batch of CR3D Filaments

filaments/siddament.json
Trial ABS before completing other filament types.
https://siddament.com.au/ is a high volume seller of filament in Australia.  Has filaments manufactured specifically for them.
=> Initial upload of siddament.json

filaments/esun.json, materials.json
Added more materials and colors from ESUN website.
=> Added materials from ESUN 

filaments/fusion.json
=> Add Fusion

filaments/extrudr.json, materials.json
Added filament profiles from the Austrian filament manufacturer [Extrudr](https://extrudr.com/)
=>  added all current Extrudr filaments

filaments.schema.json, filaments/Numakers.json, scripts/compile_filaments.py
Added all of Numaker's published filaments. 
www.numakers.com
=> Added Numakers Filaments

filaments/bambulab.json
=> Added Bambu Lab PETG-HF

filaments/bambulab.json
Added new filament PC FR (Flame Retardant)
=> Added PC FR

filaments/bambulab.json
Added PLA-CF, PETG-CF and ASA-CF
=> Added BL CF-Filaments

filaments/sunlu.json
PETG density from Sunlu TPS sheet
=> Add Sunlu PETG and PLA+ spool weight & colours

filaments/hatchbox.json
adding Hatchbox PLA and many different colors.
=> add hatchbox pla

filaments/cc3d.json
Limited information on densities available - using common average
https://cc3dglobal.com/products/
=> Add CC3D ABS, PETG and Silk PLA

filaments/prusament.json
- add Prusament PC Blend Carbon Fiber Black
- add Prusament Ultramarine Blue PETG
=> Prusament PC Blend Carbon Fiber Black + Ultramarine Blue PETG

filaments/polymaker.json
Polymaker Panchroma Dual (Matte Chameleon (Teal-Yellow))
=> Polymaker Panchroma Dual

filaments/prusament.json
- Galaxy Black
- Galaxy Silver
- Lipstick Red
- Azure Blue
- Pearl Mouse
- Vanilla White
- Gentleman's Grey
- Army Green
- Galaxy Purple
- Jet Black
- Opal Green
- Prusa Orange
- Pineapple Yellow
- Gravity Grey
- Simply Green
- Marble Grey
- Galaxy Green
- Pristine White
- Natural
=> Prusament PLA (various colors)

filaments/polymaker.json
Data pulled from the polymaker info page plus the Technical Data Sheet. 
https://us.polymaker.com/products/polylite-cospla?variant=41068179619897
https://cdn.shopify.com/s/files/1/0548/7299/7945/files/cospla_A_and_B_TDS_5.4.pdf?v=1731951221
=> Add Polymaker CosPLA versions A & B

filaments/3djake.json
various ecoPLA filaments added for the manufacturer 3djake
=> added ecoPLA filaments from 3djake

filaments/gst3d.json
Add filament currently available from https://gst3d.eu/
=> Add GST3D filament

filaments/voxel.json, filaments/voxelpla.json
Added one PETG and 3 PLA filaments.
=> Added VOXELPLA

filaments/fusion.json
=> Add Fusion ABS1.5 Natural

filaments/anycubic.json
Added black PETG and PLA for Anycubic Filament
=> initial add for ANYCUBIC

filaments/voxelpla.json
fat fingered weight in initial add.
=> Fixed weight on PETG

filaments/elegoo.json
Adding additional Elegoo RAPID PLA+ colours
=> Add additional Elegoo RAPID PLA+ colours

filaments/polymaker.json
Polymaker supplied hex codes for ALL of there Polylite ABS filaments.
=> Polymaker additional ABS

filaments/bambulab.json
- New Support for PLA https://store.bambulab.com/products/support-for-pla-new
- new TPU 85A and 90A https://store.bambulab.com/products/tpu-85a-tpu-90a
=> Add new BambuLab filaments

filaments/3djake.json
Added 3DJake ASA. Details from their website: https://www.3djake.com/3djake/asa-black
Converted the color from the RAL values they state.
=> Add 3DJake ASA

filaments/esun.json
Adds eun PLA-Luminous (https://www.esun3d.com/epla-luminous-product/)
=> Add esun PLA-Luminous

filaments/creality.json
Added Hyper ABS and Hyper PLA (with RFID), plus extra colours for standard PLA.
=> Updates to creality filaments

filaments/spectrum.json
Create spectrum.json and add PCTG.
=> Create spectrum.json and add PCTG

filaments/sunlu.json
Added Transparent, Transparent Yellow, Transparent Red, Transparent Purple, Transparent Orange, Transparent Green and Transparent Blue
=> Added SUNLU PETG Transparent Variants

filaments/elegoo.json
Added missing PETG Pro filament and respective colors
https://eu.elegoo.com/products/petg-pro-filament-1-75mm-colored-1kg
=> Added Elegoo PETG Pro filament

filaments/addnorth.json
Added all filaments from the Swedish filament manufacturer, add:north. 
[https://addnorth.se](https://addnorth.se)
=> Add all addnorth filaments
